# Generated by Django 4.2.7 on 2023-11-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_pictures'),
        ),
    ]
