# Generated by Django 4.2.7 on 2023-11-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillapp', '0004_userprofile_proficiency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='proficiency',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='expertiese_level',
            field=models.CharField(choices=[('FR', 'High'), ('SO', 'Medium'), ('JR', 'Low')], default='JR', max_length=2),
        ),
    ]
