# Generated by Django 4.2.7 on 2023-11-13 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillapp', '0005_remove_userprofile_proficiency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='expertiese_level',
            field=models.CharField(blank=True, choices=[('FR', 'High'), ('SO', 'Medium'), ('JR', 'Low')], default='JR', max_length=2, null=True),
        ),
    ]
