# Generated by Django 4.2.7 on 2023-11-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillapp', '0006_alter_userprofile_expertiese_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='expertiese_level',
            field=models.CharField(blank=True, choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='LOW', max_length=8, null=True),
        ),
    ]
